remote_theme: "mmistakes/minimal-mistakes@4.16.3"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "neon"
title: "Developer Note"
name: "Jaxon's Notebook"
logo: "/asset/logo/logo_jaxon_pornhub_style.png"
repository: "tianhaoz95/developer-note"
read_time: true
words_per_minute: 200
comments:
  provider: "disqus"
  disqus:
    shortname: "jaxon-chiaus-developer-note"